spring:
  datasource:
    url: ${DB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

logging:
  level:
    root: warn
#    org.springframework.security: debug
#    com.freedrawing.springplus: trace

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET_KEY}